services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - ./model_cache:/model_cache
    command: >
      sh -c "python download_models.py && 
            uvicorn docGPT.main:app --host 0.0.0.0 --port 8000 --reload --loop asyncio --log-level info"
    networks:
      - share-network
    env_file:
      - .env.docker
  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - transport.host=127.0.0.1
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - share-network
    healthcheck:
      interval: 30s
      retries: 10
      test: curl -s http://elasticsearch:9200/_cluster/health | grep -vq '"status":"red"'
    env_file:
      - .env.docker

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.client
    command: streamlit run app.py
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://app:8000/api
      - WS_URL=ws://app:8000
    restart: always
    depends_on:
      - app
    networks:
      - share-network
    env_file:
      - .env.docker

volumes:
  elasticsearch_data:
networks:
  share-network:

