FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml *.lock README.md ./
RUN pip install uv
RUN uv venv .venv
RUN uv sync --only-group client

COPY /client .

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8501